a=10
print('a=',a)
print(type(a))
a=a-0.23
print('a=',a)
print(type(a))
a='r'
print('a=',a)
print(type(a))
a=true
print('a=',a)
print(type(a))
a=[1,3,6,3,9]
print('a=',a)
print(type(a))
a={1,4,7,2,9}
print('a=',a)
print(type(a))
a=(1,5.9,true,'python',['c','cpp','java'],{6,4,2,0})
print('a=',a)
print(type(a))
a={1:'amir',2:'balu',3:'chandhu',4:'david'}
print('a=',a)
print(type(a))
a=range(10,20)
print('a=',a)
print(type(a))
